version: '3.5'
services:
  proposta-app:
    image: proposta-app
    environment:
      spring.profiles.active: prod
    depends_on:
       rabbit-mq:
         condition: service_healthy
    ports:
      - "8080:8080"
  rabbit-mq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      timeout: 5s
      interval: 5s
      retries: 3
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 2210
      POSTGRES_DB: propostadb